/*
 * Центр аутентификации
 * API демонстрационного приложения \"Центр аутентификации\"
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.peneksglazami.tarantool.demo.model.rest;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.github.peneksglazami.tarantool.demo.model.rest.UserStatus;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * UserGroupUpdateRequest
 */


public class UserGroupUpdateRequest {
  @JsonProperty("groupId")
  private String groupId = null;

  @JsonProperty("newStatus")
  private UserStatus newStatus = null;

  public UserGroupUpdateRequest groupId(String groupId) {
    this.groupId = groupId;
    return this;
  }

   /**
   * Идентификатор группы, к которому должна принадлежать учётная запись
   * @return groupId
  **/
  @Schema(required = true, description = "Идентификатор группы, к которому должна принадлежать учётная запись")
  public String getGroupId() {
    return groupId;
  }

  public void setGroupId(String groupId) {
    this.groupId = groupId;
  }

  public UserGroupUpdateRequest newStatus(UserStatus newStatus) {
    this.newStatus = newStatus;
    return this;
  }

   /**
   * Get newStatus
   * @return newStatus
  **/
  @Schema(required = true, description = "")
  public UserStatus getNewStatus() {
    return newStatus;
  }

  public void setNewStatus(UserStatus newStatus) {
    this.newStatus = newStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserGroupUpdateRequest userGroupUpdateRequest = (UserGroupUpdateRequest) o;
    return Objects.equals(this.groupId, userGroupUpdateRequest.groupId) &&
        Objects.equals(this.newStatus, userGroupUpdateRequest.newStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupId, newStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserGroupUpdateRequest {\n");
    
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    newStatus: ").append(toIndentedString(newStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
